In [2]:
import pandas as pd
import numpy as np
from os import listdir
from os.path import isfile, join

In [12]:
mypath = 'C:\\Users\\DFNO\\fin\\hh\\'
files = [i for i in listdir(mypath) if isfile(join(mypath, i))]
print(files)

['cpp151120.csv', 'cppres151120.csv', 'dj040121.csv', 'ds040121.csv', 'ds151120.csv', 'dsres040121.csv', 'dsres151120.csv', 'java040121.csv', 'javares040121.csv', 'javares151120.csv', 'js040121.csv', 'js151120.csv', 'jsres040121.csv', 'jsres151120.csv', 'php040121.csv', 'php151120.csv', 'phpres040121.csv', 'phpres151120.csv', 'py040121.csv', 'py151120.csv', 'pyres040121.csv', 'pyres151120.csv', 'scala040121.csv', 'scala151120.csv', 'scalares151120.csv']

In [28]:
for i in files:
    print(i)
    df = pd.read_csv(mypath + i)
    df.columns = ['tag', 'val']
    print(df)
    df.to_csv(i, index=False, sep=';')

cpp151120.csv
                      tag  val
0                     C++  590
1                   Linux  332
2                     Git  183
3                   C/C++  177
4                      Qt  170
..                    ...  ...
672                  САОД    1
673               Network    1
674         Бизнес-анализ    1
675  Планирование карьеры    1
676                   API    1

[677 rows x 2 columns]
cppres151120.csv
                            tag   val
0                           C++  1342
1                           Git   928
2                         C/C++   842
3                           ООП   808
4                         Linux   787
...                         ...   ...
4361                         СИ     1
4362               QML/Qt Quick     1
4363  STM32 (Cortex-M3, M4, M7)     1
4364     Рисование схем в P-CAD     1
4365         Организация встреч     1

[4366 rows x 2 columns]
dj040121.csv
                          tag  val
0            Django Framework   46
1                      Python   46
2   Английский — B1 — Средний   23
3                        HTML   22
4                  PostgreSQL   21
..                        ...  ...
68                        XML    1
69                Restful API    1
70                        PHP    1
71                       PHP5    1
72                       Sass    1

[73 rows x 2 columns]
ds040121.csv
                           tag  val
0                       Python  180
1                          SQL  106
2                  Data Mining   69
3    Математическая статистика   35
4                Анализ данных   29
..                         ...  ...
244                     Gensim    1
245               Scikit-learn    1
246                PolyAnalyst    1
247       Time Series Analysis    1
248                 Qlik Sense    1

[249 rows x 2 columns]
ds151120.csv
                           tag  val
0                       Python  190
1                          SQL  106
2                  Data Mining   86
3    Математическая статистика   39
4                          C++   35
..                         ...  ...
258          Marchine Learning    1
259     Технический английский    1
260                       СУБД    1
261       Регрессионный анализ    1
262                  нейросети    1

[263 rows x 2 columns]
dsres040121.csv
                             tag   val
0                         Python  1200
1                            SQL   774
2                            Git   480
3                  Data Analysis   366
4                         Pandas   341
...                          ...   ...
3085  Cross-platform development     1
3086           Code Optimization     1
3087          System Integration     1
3088                    ab-tests     1
3089            Hadoop/MapReduce     1

[3090 rows x 2 columns]
dsres151120.csv
                                            tag   val
0                                        Python  1157
1                                           SQL   744
2                                           Git   451
3                                 Data Analysis   357
4                                        Pandas   319
...                                         ...   ...
2961                     Business communication     1
2962                           Psychophysiology     1
2963                                        EEG     1
2964                                 Subversion     1
2965  базовые навыки программирования на Python     1

[2966 rows x 2 columns]
java040121.csv
                  tag   val
0                Java  1430
1    Spring Framework   924
2                 Git   547
3                 SQL   513
4          PostgreSQL   414
..                ...   ...
730      Cytoscape.js     1
731     ClojureScript     1
732       Apache NIFI     1
733         HIbernate     1
734            JAX-WS     1

[735 rows x 2 columns]
javares040121.csv
                                tag   val
0                              Java  2731
1                               Git  2214
2                               SQL  1734
3                  Spring Framework  1644
4                               ООП  1437
...                             ...   ...
5189  Навыки составления отчетности     1
5190                       testrail     1
5191                          Web3j     1
5192                 Basics of Java     1
5193                    IBM Bluemix     1

[5194 rows x 2 columns]
javares151120.csv
                                                   tag  val
0                                           JavaScript  398
1                                                  Git  277
2                                                HTML5  237
3                                                  CSS  225
4                                                 HTML  218
..                                                 ...  ...
880                              Django REST Framework    1
881  Знания HTML,CSS,JS. Работа с Webpack,SASS,Git,...    1
882                                       React, Redux    1
883                                   Customer Support    1
884                                           HTML/PUG    1

[885 rows x 2 columns]
js040121.csv
                  tag  val
0          JavaScript  724
1                 Git  343
2             Node.js  342
3                 CSS  253
4                HTML  188
..                ...  ...
599         Beanstalk    1
600              LAMP    1
601  MS Visual Studio    1
602               RDS    1
603            Koa.js    1

[604 rows x 2 columns]
js151120.csv
                  tag  val
0          JavaScript  835
1             Node.js  393
2                 Git  388
3                 CSS  272
4                HTML  232
..                ...  ...
624              twig    1
625              JDBC    1
626     Java Servlets    1
627  Start-up project    1
628       SASS / LESS    1

[629 rows x 2 columns]
jsres040121.csv
                               tag   val
0                       JavaScript  2130
1                              Git  1486
2                            HTML5  1224
3                              CSS  1181
4                             HTML  1161
...                            ...   ...
3776                 Решение задач     1
3777                    Надежность     1
3778  Внутренняя оптимизация сайта     1
3779  администрирование баз данных     1
3780    Oracle Application Express     1

[3781 rows x 2 columns]
jsres151120.csv
                           tag   val
0                   JavaScript  2132
1                          Git  1474
2                        HTML5  1245
3                          CSS  1184
4                         HTML  1159
...                        ...   ...
3727              Любопытность     1
3728  Последовательный перевод     1
3729               Flux/Reflux     1
3730                      CQRS     1
3731           modx revolution     1

[3732 rows x 2 columns]
php040121.csv
                        tag   val
0                       PHP  1268
1                     MySQL   921
2                       Git   797
3                JavaScript   670
4                       ООП   499
..                      ...   ...
595             html/js/css     1
596                 HubSpot     1
597  Продажи через интернет     1
598        Start-up project     1
599            Turbo Pascal     1

[600 rows x 2 columns]
php151120.csv
                  tag   val
0                 PHP  1374
1               MySQL  1051
2                 Git   873
3          JavaScript   713
4                 ООП   586
..                ...   ...
620                1C     1
621  командная работа     1
622      IP телефония     1
623  разработка сайта     1
624         Tarantool     1

[625 rows x 2 columns]
phpres040121.csv
                            tag   val
0                         MySQL  2821
1                           PHP  2704
2                    JavaScript  2508
3                        jQuery  2126
4                          HTML  2024
...                         ...   ...
4416              Shop-Script 6     1
4417                     php 7,     1
4418         Хорошие знания PHP     1
4419  Хорошие знания Javascript     1
4420                    RestAPI     1

[4421 rows x 2 columns]
phpres151120.csv
                                                 tag   val
0                                              MySQL  2830
1                                                PHP  2733
2                                         JavaScript  2525
3                                             jQuery  2135
4                                               HTML  2034
...                                              ...   ...
4395                               Опыт работы с Git     1
4396                Хорошие знания jQuery, CSS, HTML     1
4397  Хорошее знание SQL, и оптимизации SQL-запросов     1
4398                       Интернет-магазин OpenCART     1
4399                     Понимаю структуру ООП и MVC     1

[4400 rows x 2 columns]
py040121.csv
                  tag  val
0              Python  806
1    Django Framework  328
2          PostgreSQL  305
3                 Git  305
4               Linux  262
..                ...  ...
538             Jinja    1
539   Деловое общение    1
540           AioHTTP    1
541          Highload    1
542      Yandex Cloud    1

[543 rows x 2 columns]
py151120.csv
                  tag  val
0              Python  831
1    Django Framework  315
2          PostgreSQL  313
3                 Git  296
4               Linux  263
..                ...  ...
573               CNN    1
574     deep learning    1
575             keras    1
576            opencv    1
577                IT    1

[578 rows x 2 columns]
pyres040121.csv
                            tag   val
0                        Python  3180
1                           Git  2104
2              Django Framework  1649
3                         Linux  1632
4                           SQL  1431
...                         ...   ...
4676                Virtual Box     1
4677  Chrome Dev Tools Protocol     1
4678                   Metabase     1
4679                Web reverse     1
4680                     PySide     1

[4681 rows x 2 columns]
pyres151120.csv
                                   tag   val
0                               Python  3087
1                                  Git  2021
2                     Django Framework  1630
3                                Linux  1581
4                                  SQL  1367
...                                ...   ...
4499                       Async/await     1
4500             Разработка требований     1
4501  Easy to learn and use new things     1
4502       Good problem solving skills     1
4503   умение разобраться в чужом коде     1

[4504 rows x 2 columns]
scala040121.csv
                       tag  val
0                    SCALA   65
1                     Java   34
2                      SQL   13
3                     Akka   12
4                    Linux   12
..                     ...  ...
93                  jQuery    1
94                    Hive    1
95                    HDFS    1
96  Управление разработкой    1
97                 fintech    1

[98 rows x 2 columns]
scala151120.csv
                  tag  val
0               SCALA   73
1                Java   37
2                 SQL   17
3                 Git   16
4               Linux   16
..                ...  ...
100         No SQL DB    1
101            Mac Os    1
102  Spring Framework    1
103             MySQL    1
104       Базы данных    1

[105 rows x 2 columns]
scalares151120.csv
                 tag  val
0              SCALA   40
1               Java   29
2                Git   19
3                SQL   17
4              Linux   15
..               ...  ...
272           Jaeger    1
273       ClickHouse    1
274  spark-streaming    1
275            Latex    1
276      soft skills    1

[277 rows x 2 columns]

In [15]:
df = pd.read_csv(mypath + 'py040121.csv')
df.columns = ['tag', 'val']
df.to_csv('py040121.csv', index=False, sep=';')

                  tag  val
0              Python  806
1    Django Framework  328
2          PostgreSQL  305
3                 Git  305
4               Linux  262
..                ...  ...
538             Jinja    1
539   Деловое общение    1
540           AioHTTP    1
541          Highload    1
542      Yandex Cloud    1

[543 rows x 2 columns]